# Generated by Django 5.2.1 on 2025-06-11 20:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endereco', models.CharField(max_length=255)),
                ('tipo_servico', models.CharField(choices=[('pedreiro', 'Pedreiro'), ('marido_de_aluguel', 'Marido de Aluguel'), ('piscineiro', 'Piscineiro')], max_length=20)),
                ('descricao', models.TextField()),
                ('data_solicitacao', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
