# Generated by Django 5.2.8 on 2025-11-24 23:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='servico',
            name='autonomo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicos_atendidos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='servico',
            name='data_visita',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servico',
            name='recusado_por',
            field=models.ManyToManyField(blank=True, related_name='vagas_recusadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='servico',
            name='status',
            field=models.CharField(choices=[('aberto', 'Aberto'), ('proposta_enviada', 'Proposta Enviada'), ('pendente', 'Pendente'), ('concluido', 'Concluído')], default='aberto', max_length=20),
        ),
        migrations.AddField(
            model_name='servico',
            name='valor_hora',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='servico',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes', to=settings.AUTH_USER_MODEL),
        ),
    ]
